services:
  - type: web
    name: chicago-lst-tiles
    env: docker
    rootDir: backend
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: TITILER_API_CORS_ORIGINS
        value: "*"
      - key: TITILER_API_CORS_ALLOW_METHODS
        value: "GET"
      - key: TITILER_API_CACHECONTROL
        value: "public, max-age=3600"

