services:
  - type: web
    name: chicago-lst-tiles
    env: docker
    rootDir: 08_GIS_PROJECTS/webapps/chicago_lst/backend
    plan: free
    autoDeploy: true
    healthCheckPath: /docs
    envVars:
      - key: TITILER_API_CORS_ORIGINS
        value: "*"
      - key: TITILER_API_CORS_ALLOW_METHODS
        value: "GET"
      - key: TITILER_API_CACHECONTROL
        value: "public, max-age=3600"

